environment: dev
stage: development

vault:
  role: "solr-role-dev"
  secretPath: "secret/data/solr/security/development"

solr:
  replicas: 1
  storage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: "3Gi"
          storageClassName: "nfs-pm"
      reclaimPolicy: Delete

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  JavaMem: "-Xms7g -Xmx7g"
  LogLevel: "INFO"
  Opts: "-Dsolr.environment={{ .Values.environment }},label=P4H,color=green"

zk:
  replicas: 1

  persistence:
    spec:
      resources:
        limits:
          cpu: "1"
          storage: "1Gi"
        requests:
          cpu: "1"
          storage: "1Gi"
      storageClassName: "nfs-pm"
    reclaimPolicy: Delete
