apiVersion: v1
kind: ConfigMap
metadata:
#  annotations:
#    argocd.argoproj.io/sync-wave: "0" # Волна синхронизации - выполняется первой
  name: configmap-custom
  namespace: solr-dev
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
        <Appenders>

            <Console name="STDOUT" target="SYSTEM_OUT">
                <PatternLayout>
                    <Pattern>
                        %d{yyyy-MM-dd HH:mm:ss.SSS} %-5p (%t) [%X{collection} %X{shard} %X{replica} %X{core}] %c{1.} %m%n
                    </Pattern>
                </PatternLayout>
            </Console>

            <RollingFile
                    name="RollingFile"
                    fileName="${sys:solr.log.dir}/solr.log"
                    filePattern="${sys:solr.log.dir}/solr.log.%i">
                <PatternLayout>
                    <Pattern>
                        %d{yyyy-MM-dd HH:mm:ss.SSS} %-5p (%t) [%X{collection} %X{shard} %X{replica} %X{core}] %c{1.} %m%n
                    </Pattern>
                </PatternLayout>
                <Policies>
                    <OnStartupTriggeringPolicy/>
                    <SizeBasedTriggeringPolicy size="64 MB"/>
                </Policies>
                <DefaultRolloverStrategy max="12"/>
            </RollingFile>

            <RollingFile
                    name="SlowFile"
                    fileName="${sys:solr.log.dir}/solr_slow_requests_json.log"
                    filePattern="${sys:solr.log.dir}/solr_slow_requests_json.log.%i">
                <JsonTemplateLayout/>
                <Policies>
                    <OnStartupTriggeringPolicy/>
                    <SizeBasedTriggeringPolicy size="32 MB"/>
                </Policies>
                <DefaultRolloverStrategy max="6"/>
            </RollingFile>

            <RollingFile
                    name="JsonFile"
                    fileName="${sys:solr.log.dir}/json_solr.log"
                    filePattern="${sys:solr.log.dir}/json_solr.log.%i">
                <JsonTemplateLayout/>
                <Policies>
                    <OnStartupTriggeringPolicy/>
                    <SizeBasedTriggeringPolicy size="64 MB"/>
                </Policies>
                <DefaultRolloverStrategy max="12"/>
            </RollingFile>

        </Appenders>
        <Loggers>
            <Logger name="org.apache.hadoop" level="warn"/>
            <Logger name="org.apache.solr.update.LoggingInfoStream" level="off"/>
            <Logger name="org.apache.zookeeper" level="warn"/>
            <Logger name="org.apache.solr.core.SolrCore.SlowRequest" level="info" additivity="false">
                <AppenderRef ref="SlowFile"/>
            </Logger>

            <Root level="warn">
                <AppenderRef ref="RollingFile"/>
                <AppenderRef ref="STDOUT"/>
                <AppenderRef ref="JsonFile"/>
            </Root>
        </Loggers>
    </Configuration>
  solr.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <solr>
        <solrcloud>
            <str name="host">${host:}</str>
            <int name="hostPort">${solr.port.advertise:8983}</int>
            <str name="hostContext">${hostContext:solr}</str>
            <bool name="genericCoreNodeNames">${genericCoreNodeNames:true}</bool>
            <int name="zkClientTimeout">${zkClientTimeout:30000}</int>
            <int name="distribUpdateSoTimeout">${distribUpdateSoTimeout:600000}</int>
            <int name="distribUpdateConnTimeout">${distribUpdateConnTimeout:60000}</int>
            <str name="zkCredentialsProvider">${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}</str>
            <str name="zkACLProvider">${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}</str>
        </solrcloud>

        <shardHandlerFactory name="shardHandlerFactory" class="HttpShardHandlerFactory">
            <int name="socketTimeout">${socketTimeout:600000}</int>
            <int name="connTimeout">${connTimeout:60000}</int>
        </shardHandlerFactory>
    </solr>
